import type { Card } from '../types/cards';

export const ownProductionCards: Card[] = [
   {
      cardId: 4_1,
      type: 'clamp',
      title: 'Хомут для средней нагрузки 1/4” (d12-15мм)',
      link: 'src/pages/catalog.html',
      imgL: 'https://hommet.ru/media/hommet_cache/a4/d2/a4d2ebfe55f43428d4e72d9e11eb7978.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/средней_нагрузки.webp',
   },
   {
      cardId: 4_2,
      type: 'clamp',
      title: 'Усиленный хомут с уплотнением 1 1/2” (47-53мм)',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/8f/e7/8fe7d34d803730ef385b67578c25b30d.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/ilk_(convert.io).webp',
   },
   {
      cardId: 1_1,
      type: 'dms',
      title: 'Крепление двойное Удлиненное Хоммет',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/43/54/43546bf919d1ed64eb4826d2357a8713.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/удл.webp',
   },
   {
      cardId: 3_1,
      type: 'prof',
      title: 'Шпилька забивная М8*220 с дюбелем',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/d8/6d/d86d91fa857142218529428bd9895101.png',
      imgB: 'https://hommet.ru/media/uploads/хомуты/шпил.png',
   },
   {
      cardId: 1_2,
      type: 'dms',
      title: 'Торцевой элемент металлический',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/b8/be/b8be09e7996aed36e386ee00382f6f21.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/иа_(convert.io).webp',
   },
   {
      cardId: 1_3,
      type: 'dms',
      title: 'Профиль Хоммет 4,5 метра',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/ab/e6/abe67c6742f14b2c76eeb8b41d512d47.webp',
      imgB: 'https://hommet.ru/media/products/images/проф_convert.io.webp',
   },
   {
      cardId: 4_4,
      type: 'clamp',
      title: 'Хомут для сверхтяжелой нагрузки 2 1/2” (d73-80мм)',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/b8/81/b88110bcb09f1bdb2e54690d1bede2f8.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/1_хомуты_с_уплотнением_для_сверх_тяжелой_нагрузки_440.webp',
   },
   {
      cardId: 4_5,
      type: 'clamp',
      title: 'Вентиляционный хомут с резиновым уплотнением с гайкой М8 315',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/d1/66/d166dba2cca8f66439a83a2d2c803cc6.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/вентиляционный_хомут_с_резиновым_уплотнением_с_гайкой_м8.webp',
   },
   {
      cardId: 4_6,
      type: 'clamp',
      title: 'Опора для средней нагрузки двухомутовая',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/45/cd/45cd81121db2b0210bac0fd3e0517473.webp',
      imgB: 'https://hommet.ru/media/uploads/хомуты/пт_(convert.io).webp',
   },
   {
      cardId: 1_6,
      type: 'dms',
      title: 'Комплект петель для профиля Хоммет',
      link: '#',
      imgL: 'https://hommet.ru/media/hommet_cache/c2/25/c2251fc71c6ac206e70b75579efd854a.png',
      imgB: 'https://hommet.ru/media/products/images/kompl.png',
   },
];
