import type { Card } from '@/utils/types/cards';

const clampL = [
   'https://hommet.ru/media/hommet_cache/2a/6a/2a6a710084c73787075d18491f389b90.png',
];
const clampB = ['https://hommet.ru/media/products/images/nerzh_KpCprAy.png'];
export const clampsStainless: Card[] = [
   {
      cardId: '4_3_1',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 3/8” (d15-20мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-3-8-15-20mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_2',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 1/2” (d20-24мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-1-2-20-24mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_3',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 3/4” (d25-30мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-3-4-25-30mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_4',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 1” (d32-37мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-1-32-37mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_5',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 1 1/4” (d40-46мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-1-1-4-40-46mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_6',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 1 1/2” (d47-53мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-1-1-2-47-53mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_7',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 2” (d58-64мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-2-58-64mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_8',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 2 1/2” (d73-80мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-2-1-2-73-80mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_9',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 3” (d87-94мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-3-87-94mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_10',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 4” (d105-115мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-4-105-115mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_11',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 5” (d132-137мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-5-132-137mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_12',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 6” (d159-163мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-6-159-163mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_13',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 8” (d216-226мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-8-216-226mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_14',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 10” (d266-274мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-10-266-274mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_15',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 12” (d308-324мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-12-308-324mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_16',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 14” (d340-356мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-14-340-356mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_17',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 20” (d490-525мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-20-490-525mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_18',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 2х25 16” (d390-415мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-16-390-415mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_19',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 1/2” (d20-24мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2kh25-1-2-20-24mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_20',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 3/4” (d25-30мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-3-4-25-30mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_21',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 1” (d32-37мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-1-32-37mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_22',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 1 1/4” (d40-46мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-1-1-4-40-46mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_23',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 1 1/2” (d47-53мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-1-1-2-47-53mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_24',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 2” (d58-64мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2-58-64mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_25',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 2 1/2” (d73-80мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-2-1-2-73-80mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_26',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 3” (d87-94мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-3-87-94mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_27',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 4” (d105-115мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-4-105-115mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_28',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 5” (d132-137мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-5-132-137mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_29',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 6” (d159-163мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-6-159-163mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_30',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 8” (d216-226мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-8-216-226mm/',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_31',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 10” (d266-274мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-3kh30-3-8-15-20mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_32',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 12” (d308-324мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-12-308-324mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_33',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 14” (d340-356мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-14-340-356mm',
      imgL: clampL,
      imgB: clampB,
   },
   {
      cardId: '4_3_34',
      title: 'Хомут для тяжелой нагрузки из нержавеющей стали 3х30 16” (d390-415мм)',
      pathname: 'product/khomut-iz-nerzhaveiki-16-390-415mm',
      imgL: clampL,
      imgB: clampB,
   },
];
